version: "3"

services:
  api-solid-pg:
    image: bitnami/postgresql:latest
    build: .
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USERNAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=apisolid
